services:
        postgres:
                image: postgres:14.2-alpine
                restart: always
                ports:
                        - 5432:5432
                environment:
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_DB: parking-control-db
                volumes:
                        - "./pgdata:/var/lib/postgresql/data"

        pgadmin4:
                image: dpage/pgadmin4
                restart: always
                depends_on:
                        - postgres
                ports:
                        - 80:80
                environment:
                        - PGADMIN_DEFAULT_EMAIL=user@domain.com
                        - PGADMIN_DEFAULT_PASSWORD=SuperSecret